
services:
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: youseffelgindy
      POSTGRES_PASSWORD: youseffelgindy
      POSTGRES_DB: blog_api_development
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "bundle exec rails db:migrate && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://youseffelgindy:youseffelgindy@db:5432/postgres
      REDIS_URL: redis://redis:6379/1

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://youseffelgindy:youseffelgindy@db:5432/postgres
      REDIS_URL: redis://redis:6379/1

volumes:
  pgdata:
